# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: 
  adapter: postgresql
  encoding: unicode
  database: pitchify_development
  pool: 5
  username: socialmenu
  host: localhost 

test:              
  adapter: postgresql
  encoding: unicode
  database: pitchify_test
  pool: 5
  username: socialmenu
  host: localhost

production:              
  adapter: postgresql
  encoding: unicode
  database: pitchify_production
  pool: 5
  username: socialmenu
  host: localhost
